language: java

addons:
  sonarcloud:
    organization: "bigfatmoon"
script:
  - mvn clean jacoco:prepare-agent package sonar:sonar -Dsonar.login=${SONAR_TOKEN} -DcovToken=${COVERALLS_TOKEN}
after_success:
  - mvn clean test jacoco:report coveralls:report